siteTitle="GeoAvalanche"
tagLine="Snow avalanche spatial data infrastructure for avalanche risk insight"
linkPrefix = "/"
githubUrl = "https://github.com/geoavalanche/geoavalanche-client"
twitterId = "geoavalanche"
twitterUrl = "https://twitter.com/geoavalanche"
discussUrl = "https://discord.gg/Jf3pGjf"
mapLink = "/map/"
docsLink = "/docs/introduction/"
apiLink = "/api/"
gettingStartedLink = "/docs/gettingstarted/requirements/"
apiBaseUrl = "/api"
githubDocsBaseUrl = "https://github.com/geoavalanche/geoavalanche-client/tree/master/README.MD"